### ISSUE TITLE
Doesn't really work well

### ISSUE THREAD

**Issue by OverRatedAU** [UnrealisticDev/Renom#11]
Missing class APIs and also misses changing headers of classes, most likely safer to use PowerGERP to rename with.

**Comment by msmoiz** [comment]
This is not useful feedback. You are welcome to submit a bug report if there is a bug in currently supported functionality or a feature request if you are interested in seeing new functionality introduced. In either event, please provide actionable information that describes the problem you are trying to solve in detail.

**Comment by OverRatedAU** [comment]
I have reported the issue it doesn't rename APIs and also doesn't search and change headers to classes which are include within the project being renamed.

**Comment by msmoiz** [comment]
Regarding changing class APIs, I assume you are referring to the module export macro (e.g., `MYMODULE_API`). These macros are no longer updated as part of the project rename process. Instead, they can (and should) only be changed when renaming a module. To do this, use the rename module workflow included with the latest version of the tool to rename the primary game module for your project (or another module, if there is more than one). If this does not solve the issue, please provide detailed steps to reproduce the problem and a minimal project for debugging.

```shell
$ renom
[ Welcome to Renom ]
? Choose a workflow:
  Rename a project
  Rename a plugin
  Rename a target
> Rename a module
```

Regarding changing headers, this is not something that will likely be supported in the near future due to the complexities involved. I would recommend using PowerGREP as a supplement to Renom to handle tasks like this that are not supported out of the box.

**Comment by OverRatedAU** [comment]
I used the Rename Module which missed a number of the class MACROS, I use the packaged version of the tool which should be the latest? Renaming headers should be a simple and apart of renaming a project as it changes the folder name, not hard to search for headers and rename them after all.

**Comment by msmoiz** [comment]
Unless you can provide a sample project and clear description of steps to reproduce the macro issue, there is not much I can do.

**Comment by OverRatedAU** [comment]
Yeah sadly I used your tool on a large project and can't supply you with a sample project to test, ether way the tool did help in the process I was just reporting user feedback.
