### ISSUE TITLE
Project rename failed

### ISSUE THREAD

**Issue by Nicoeevee** [UnrealisticDev/Renom#3]
![image](https://user-images.githubusercontent.com/16593867/168084262-39ffc6ae-4d4f-4861-85a0-117f5179310b.png)
Official demo project
![image](https://user-images.githubusercontent.com/16593867/168084768-f756ba54-75e9-4738-84cd-8908c7f85adc.png)

**Comment by msmoiz** [comment]
Looks like the standard project file names may have changed for UE5

**Comment by msmoiz** [comment]
Upon further review, this looks like an issue with the Lyra sample rather than with UE5 in general. Tested with a fresh UE5 project, and it works fine; in other words, standard project structure has not changed. Main trouble with handling Lyra is that it deviates substantially from the standard project structure. For instance, the *DefaultEngine.ini* config file lists the game name as `LyraStarterGame`, but the primary game module is called `LyraGame` (no *Starter*) and the project targets (*.Target.cs*) are similarly using the *Lyra* base (*LyraGame*, *LyraEditor*, *LyraGameEOS*).

To make renaming plug-and-play, we make one major assumption: the project, target files, build files, and source files share the same base name. Because that assumption fails in the case of Lyra, it is guesswork to determine which files to rename and which to skip.

It would be non-trivial to support this use case (either by seeking more user input or by adding heuristics); marking as *won't fix* for now. May revisit if time permits.

In the meantime, the workaround is to [review the source material](https://unrealistic.dev/posts/rename-your-project-including-code) and rename manually using those guidelines.
