### ISSUE TITLE
List of all the issue that I faced

### ISSUE THREAD

**Issue by hcabel** [UnrealisticDev/Renom#6]
Hi, I tried your tool and sadly it couldn't help me, but I still really like your tool so here is the list of issues that I faced:

### 1. I put your exe into the project folder
Your tool couldn't rename the project folder because he was actually in used by himself.

### 2. Multiple module handling
I have multiple module in my project and your exe didn't rename them all.
 
### 3. Tool stop if he didn't find the file: '[ProjectName].h' or  '[ProjectName].cpp'
Your tool tried to rename '[ProjectName].h' but since I'm using modules I named my file '[ProjectName]Module.h'.
(To fix that I had to create a fake file so your script can move on)

### 4. It didn't rename all my files
Most of my files are starting with '[ProjectName][ClassName]' and most of them hasn't been renamed.

### 5. Better sentence to ask for project location
In my view when asking for the project path 'Project Root' is not accurate enough instead I would print: 'Project Root Path' 

### 6. Renaming solution file
I don't know if you handled '.sln' but my '.vscode-workspace' hasn't been renamed

Even though this sounds pretty negative, I genuinely want your tool to improve (that why I'm taking time to report an issue).
Here is a list of thing that I like the most:

- The error handling is really great (I was impress that it tell me that another process where using the file instead of just saying that it couldn't rename the folder)
- The UI is nice nothing fancy but it does the job pretty well
- Easy to use
- You gave a exe to download instead of having to build on our own
- Being able to revert (This one is my favorite)

PS: In those 'issues' some of them are not really essential, but I still include them to make your tool has seamless has possible. :)

**Comment by msmoiz** [comment]
Thanks for your notes and the kind feedback Hugo. To address the identified issues in turn:

1. The .exe should be installed somewhere on your system PATH but not in the project root directory. Running it from the project root directory will prevent that directory from being renamed.
2. This is a great suggestion. I have added basic multi-module support in the latest release (0.1.5).
3. As part of multi-module support, this issue has been addressed as well. The program no longer searches for a file with a specific name but instead hunts for the file that contains the `IMPLEMENT_MODULE` macro and is now much more flexible.
4. This is a tricky problem to solve without intimate knowledge of the source files, which is a non-trivial task. In addition, it is not always clear that a user wants to rename a class or source file even when renaming the project. This is out-of-scope in the short-term and likely the long-term as well based on the required investment.
5. Another good suggestion. Instead of "Project Root", the prompt now reads "Project root directory path."
6. The VS Code workspace is not something I am familiar with, but similar to the Visual Studio workspace, I recommend deleting and re-generating it after running the program if possible.

Thanks again!
